services:
  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn gog.wsgi:application --bind 0.0.0.0:8000"
    expose:
      - "8000"
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis
      - celery
    volumes:
      - static_volume:/gogserver/gog/staticfiles
    environment:
      - REDIS_URL=redis://redis:6379
  db:
    image: "postgres:latest"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env.prod
    environment:
      POSTGRES_PASSWORD: gog_password_prod

  nginx:
    build: ./nginx
    ports:
      - "1337:80"
    depends_on:
      - web
    volumes:
      - static_volume:/gogserver/gog/staticfiles

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A gog worker --loglevel=info
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis
    volumes:
      - static_volume:/gogserver/gog/staticfiles
    environment:
      - REDIS_URL=redis://redis:6379

volumes:
  postgres_data:
  static_volume:
